gemfile: Gemfile

PreCommit:
  BundleCheck:
    enabled: true

  ExecutePermissions:
    enabled: true
    exclude:
      - 'bin/scss-lint'

  HardTabs:
    enabled: true

  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']

  TrailingWhitespace:
    enabled: true

  TravisLint:
    enabled: true
    command: ['bundle', 'exec', 'travis']
    flags: ['lint', '--skip-version-check']

  YamlSyntax:
    enabled: true
