AmbiguousRegexpLiteral:
  Enabled: false

AccessModifierIndentation:
  EnforcedStyle: outdent

AssignmentInCondition:
  Enabled: false

# Enforcing this results in a lot of unnecessary indentation.
ClassAndModuleChildren:
  Enabled: false

CollectionMethods:
  Enabled: false

# Ruby 1.8.7 only supports trailing dots in method chains, but Rubocop still
# reports it as an error for method calls chained onto do...end blocks. That's
# too much noise, so remove it.
DotPosition:
  Enabled: false

FormatString:
  Enabled: false

IfUnlessModifier:
  Enabled: false

LineLength:
  Max: 100

MethodLength:
  Max: 20

SignalException:
  Enabled: false

SpecialGlobalVars:
  Enabled: false

TrailingComma:
  Enabled: false

Void:
  Enabled: false
